// publications.ts

export type PublicationLink = {
  label: string;
  href: string;
};

export type PublicationDetail = {
  abstract?: string;
  pdf?: string;
  bibtex?: string;
  hero?: { src: string; alt: string };
};

export type Author = {
  name: string;
  highlight?: boolean;
};

export type Publication = {
  slug: string;
  year: number;
  title: string;
  authors: Author[];
  venue: string;
  image: { src: string; alt: string };
  links: PublicationLink[];
  highlight?: string;
  detail?: PublicationDetail;
};

export const publications: Publication[] = [
  //2026
      {
    slug: "hlc-llm",
    year: 2026,
    title:
      "How Do LLMs See Charts? A Comparative Study on High-Level Visualization Comprehension in Humans and LLMs",
    authors: [
      { name: "Hyotaek Jeon" },
      { name: "Hyunwook Lee" },
      { name: "Minjeong Shin" },
      { name: "Tapendra Pandey", highlight: true },
      { name: "Joohee Kim" },
      { name: "Shinwook Seon" },
      { name: "Daeun Jeong" },
      { name: "Sungahn Ko" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      
    ],
    venue:
      "In Proceedings of EuroVis 2026: Eurographics Conference on Visualization.",
    links: [{ label: "DOI", href: "https://doi.org/10.1111/cgf.70450" },
      { label: "PDF", href: "https://arxiv.org/pdf/2604.08959" }],
    image: {
      src: "/publications/hlcllm.png",
      alt: "HLCLLM Image",
    },
    detail: {
      hero: {
        src: "/publications/hlcllm.png",
        alt: "HLCLLM Image",
      },
      pdf: "https://arxiv.org/abs/2604.08959",
      abstract: `Designers often create visualizations to achieve specific high-level analytical or communication goals. These goals require people to extract complex and interconnected data patterns. Prior perceptual studies of visualization effectiveness have focused on low-level tasks, such as estimating statistical quantities, and have recently explored high-level comprehension of visualization. Despite the growing use of Large Language Models (LLMs) as visualization interpreters, how their interpretations relate to human understanding or what reasoning processes underlie their responses remains insufficiently understood. In this work, we explore LLMs' visualization comprehension, examining the alignment between designers' communicative goals and what their audience sees in a visualization. We have conducted a qualitative study to investigate the gap between human interpretative strategies and the reasoning pathways of LLMs across three types of visualizations, line graphs, bar graphs, and scatterplots, to identify the high-level patterns generated by LLMs using three prompt conditions. Our analysis results indicate that LLMs exhibit a consistent interpretative strategy that remains unchanged across prompt constraints. Furthermore, we observe two distinct approaches: humans naturally synthesize data into trend-centric narratives, whereas LLMs persist with a structural enumeration of comparisons and numerical ranges. Lastly, we see LLMs achieve visualization comprehension through mechanisms distinct from human intuition, pointing to critical challenges and new opportunities for visualization design.`,
      bibtex: `@misc{jeon2026llmschartscomparativestudy,
      title={How Do LLMs See Charts? A Comparative Study on High-Level Visualization Comprehension in Humans and LLMs}, 
      author={Hyotaek Jeon and Hyunwook Lee and Minjeong Shin and Tapendra Pandey and Joohee Kim and Shinwook Seon and Daeun Jeong and Sungahn Ko and Ghulam Jilani Quadri},
      year={2026},
      eprint={2604.08959},
      archivePrefix={arXiv},
      primaryClass={cs.HC},
      doi={10.1111/cgf.70450},
      url={https://arxiv.org/abs/2604.08959}, 
}

}`,
    },
  },
       {
    slug: "human-mllm",
    year: 2026,
    title:
      "Seeing graphs like humans: Benchmarking computational measures and MLLMs for similarity assessment",
    authors: [
      { name: "Seokweon Jung" },
      { name: "Jeongmin Rhee" },
      { name: "Seoyoung Doh" },
      { name: "Hyeon Jeon"},
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Jinwook Seo" },
      
    ],
    venue:
      "Information Visualization, 2024.",
    links: [
      { label: "DOI", href: "https://doi.org/10.1177/14738716261434961" },
      { label: "PDF", href: "https://journals.sagepub.com/doi/pdf/10.1177/14738716261434961" }
    ],
    image: {
      src: "/publications/human-mllm.png",
      alt: "Human MLLM Image",
    },
    detail: {
      hero: {
        src: "/publications/human-mllm.png",
        alt: "Human MLLM Image",
      },
      pdf: "https://journals.sagepub.com/doi/pdf/10.1177/14738716261434961",
      abstract: `Comparing graphs to identify similarities is a fundamental task in visual analytics of graph data. To support
this, visual analytics systems frequently employ quantitative computational measures to provide automated
guidance. However, it remains unclear how well these measures align with subjective human visual perception, thereby offering recommendations that conflict with analysts’ intuitive judgments, potentially leading to
confusion rather than reducing cognitive load. Multimodal Large Language Models (MLLMs), capable of
visually interpreting graphs and explaining their reasoning in natural language, have emerged as a potential
alternative to address this challenge. This paper bridges the gap between human and machine assessment
of graph similarity through 3 interconnected experiments using a dataset of 1881 node-link diagrams.
Experiment 1 collects relative similarity judgments and rationales from 32 human participants, revealing consensus on graph similarity while prioritizing global shapes and edge densities over exact topological details.
Experiment 2 benchmarks 16 computational measures against these human judgments, identifying Portrait
divergence as the best-performing metric, though with only moderate alignment. Experiment 3 evaluates the
potential of 3 state-of-the-art MLLMs (GPT-5, Gemini 2.5 Pro, Claude Sonnet 4.5) as perceptual proxies. The
results demonstrate that MLLMs, particularly GPT-5, significantly outperform traditional measures in aligning with human graph similarity perception and provide interpretable rationales for their decisions, whereas
Claude Sonnet 4.5 shows the best computational efficiency. Our findings suggest that MLLMs hold significant
promise not only as effective, explainable proxies for human perception but also as intelligent guides that can
uncover subtle nuances that might be overlooked by human analysts in visual analytics systems.`,
      bibtex: `@article{doi:10.1177/14738716261434961,
author = {Seokweon Jung and Jeongmin Rhee and Seoyoung Doh and Hyeon Jeon and Ghulam Jilani Quadri and Jinwook Seo},
title ={Seeing graphs like humans: Benchmarking computational measures and MLLMs for similarity assessment},
journal = {Information Visualization},
volume = {0},
number = {0},
pages = {14738716261434961},
year = {2026},
doi = {10.1177/14738716261434961},
url = {https://journals.sagepub.com/doi/pdf/10.1177/14738716261434961},
}

}`,    },
  },
  {
    slug: "annotation-educator",
    year: 2026,
    title:
      "Designing Annotations in Visualization: Considerations from Visualization Practitioners and Educators",
    authors: [
      { name: "MD Rahman" },
      { name: "Devin Lange" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Paul Rosen" }, 
    ],
    venue:
      "In Proceedings of EuroVis 2026: Eurographics Conference on Visualization.",
    links: [ { label: "DOI", href: "https://doi.org/10.1111/cgf.70435" },
      { label: "PDF", href: "https://arxiv.org/pdf/2604.07691" }],
    image: {
      src: "/publications/annotation-educator.png",
      alt: "Annotation Educator Image",
    },
    detail: {
      hero: {
        src: "/publications/annotation-educator.png",
        alt: "Annotation Educator Image",
      },
      pdf: "https://arxiv.org/abs/2604.07691",
      abstract: ` Annotation is a central mechanism in visualization design that enables people to communicate key insights. Prior research has provided essential accounts of the visual forms annotations take, but less attention has been paid to the decisions behind them. This paper examines how annotations are designed in practice and how educators reflect on those practices. We conducted a two-phase qualitative study: interviews with ten practitioners from diverse backgrounds revealed the heuristics they draw on when creating annotations, and interviews with seven visualization educators offered complementary perspectives situated within broader concerns of clarity, guidance, and viewer agency. These studies provide a systematic account of annotation design knowledge in professional settings, highlighting the considerations, trade-offs, and contextual judgments that shape the use of annotations. By making this tacit expertise explicit, our work complements prior form-focused studies, strengthens understanding of annotation as a design activity, and points to opportunities for improved tool and guideline support.`,
      bibtex: `@misc{rahman2026designingannotationsvisualizationconsiderations,
      title={Designing Annotations in Visualization: Considerations from Visualization Practitioners and Educators}, 
      author={Md Dilshadur Rahman and Devin Lange and Ghulam Jilani Quadri and Paul Rosen},
      year={2026},
      eprint={2604.07691},
      archivePrefix={arXiv},
      primaryClass={cs.HC},
      doi={10.1111/cgf.70435},
      url={https://arxiv.org/abs/2604.07691}, 
}, 
}

}`,
    },
  },
    {
    slug: "redundant-is-not-redundant",
    year: 2026,
    title:
      "Redundant is Not Redundant: Automating Efficient Categorical Palette Design Unifying Color & Shape Encodings with CatPAW",
    authors: [
      { name: "Chin Tseng" },
      { name: "Arran Zeyu Wang" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Danielle Albers Szafir" },
    ],
    venue:
      "In Proceedings of ACM CHI’ 2026: ACM Conference on Human Factors in Computing Systems.",
    links: [
      { label: "DOI", href: "https://doi.org/10.1145/3772318.3791244" },
      { label: "PDF", href: "https://arxiv.org/abs/2602.06792" }
    ],
    image: {
      src: "/publications/catpaw.png",
      alt: "CatPAW Image",
    },
    detail: {
      hero: {
        src: "/publications/catpaw.png",
        alt: "CatPAW Image",
      },
      pdf: "https://arxiv.org/abs/2602.06792",
      abstract: `Colors and shapes are commonly used to encode categories in
multi-class scatterplots. Designers often combine the two channels to create redundant encodings, aiming to enhance class distinctions. However, evidence for the effectiveness of redundancy
remains conflicted, and guidelines for constructing effective combinations are limited. This paper presents four crowdsourced experiments evaluating redundant color–shape encodings and identifying high-performing configurations across different category numbers.
Results show that redundancy significantly improves accuracy in
assessing class-level correlations, with the strongest benefits for 5–8
categories. We also find pronounced interaction effects between
colors and shapes, underscoring the need for careful pairing in
designing redundant encodings. Drawing on these findings, we
introduce a categorical palette design tool that enables designers
to construct empirically grounded palettes for effective categorical
visualization. Our work advances understanding of categorical perception in data visualization by systematically identifying effective
redundant color–shape combinations and embedding these insights
into a practical palette design tool.`,
      bibtex: `@inproceedings{Tseng_2026, series={CHI ’26},
   title={Redundant is Not Redundant: Automating Efficient Categorical Palettes Design Unifying Color &amp; Shape Encodings with CatPAW},
   url={http://dx.doi.org/10.1145/3772318.3791244},
   DOI={10.1145/3772318.3791244},
   booktitle={Proceedings of the 2026 CHI Conference on Human Factors in Computing Systems},
   publisher={ACM},
   author={Tseng, Chin and Wang, Arran Zeyu and Quadri, Ghulam Jilani and Szafir, Danielle Albers},
   year={2026},
   month=apr, pages={1–18},
   collection={CHI ’26} }

}`,
    },
    highlight: "Best Paper Honorable Mention (ACM CHI 2026)",
  },
  //2025
  {
    slug: "visual-stenography",
    year: 2025,
    title:
      "Visual Stenography: Feature Recreation and Preservation in Sketches of Noisy Line Charts",
    authors: [
      { name: "Rifat Ara Proma" },
      { name: "Michael Correll" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Paul Rosen" },
    ],
    venue:
      "(in press) To appear in IEEE Transactions on Visualization and Computer Graphics 2025.",
    links: [
      { label: "DOI", href: "https://doi.org/10.1109/TVCG.2025.3626128" },
      { label: "PDF", href: "https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=11218815" }
    ],
    image: {
      src: "/publications/visual_stenography.png",
      alt: "Visual Stenography Image",
    },
    detail: {
      hero: {
        src: "/publications/visual_stenography.png",
        alt: "Visual Stenography Image",
      },
      pdf: "https://arxiv.org/abs/2510.11927",
      abstract: `Line charts surface many features in time series
data, from trends to periodicity to peaks and valleys. However,
not every potentially important feature in the data may corre-
spond to a visual feature which readers can detect or prioritize.
In this study, we conducted a visual stenography task, where
participants re-drew line charts to solicit information about the
visual features they believed to be important. We systematically
varied noise levels (SNR ≈5–30 dB) across line charts to observe
how visual clutter influences which features people prioritize in
their sketches. We identified three key strategies that correlated
with the noise present in the stimuli: the Replicator attempted
to retain all major features of the line chart including noise;
the Trend Keeper prioritized trends disregarding periodicity and
peaks; and the De-noiser filtered out noise while preserving other
features. Further, we found that participants tended to faithfully
retain trends and peaks and valleys when these features were
present, while periodicity and noise were represented in more
qualitative or gestural ways: semantically rather than accurately.
These results suggest a need to consider more flexible and
human-centric ways of presenting, summarizing, pre-processing,
or clustering time series data.`,
      bibtex: `@misc{proma2025visualstenographyfeaturerecreation,
      title={Visual Stenography: Feature Recreation and Preservation in Sketches of Noisy Line Charts}, 
      author={Rifat Ara Proma and Michael Correll and Ghulam Jilani Quadri and Paul Rosen},
      year={2025},
      eprint={2510.11927},
      archivePrefix={arXiv},
      primaryClass={cs.HC},
      url={https://arxiv.org/abs/2510.11927}, 
      doi={10.1109/TVCG.2025.3626128},
}`,
    },
  },
  {
    slug: "discrepancies-in-mental-workload",
    year: 2025,
    title:
      " Discrepancies in Mental Workload Estimation: Self-Reported versus EEG-Based Measures in Data Visualization Evaluation",
    authors: [
      { name: "Soobin Yim" },
      { name: "Sangbong Yoo" },
      { name: "Chanyoung Yoon" },
      { name: "Chanyoung Jung" },
      { name: "Chansoo Kim" },
      { name: "Yun Jang" },
      { name: "Ghulam Jilani Quadri", highlight: true },
    ],
    venue: "Preprint",
    links: [{ label: "PDF", href: "https://arxiv.org/pdf/2507.09262" }],
    image: { src: "/publications/discrepancies.png", alt: "Distortion Image" },
    detail: {
      hero: {
        src: "/publications/discrepancies.png",
        alt: "Distortion Image",
      },
      pdf: "",
      abstract: `Accurate assessment of mental workload (MW) is
crucial for understanding cognitive processes during visualization
tasks. While EEG-based measures are emerging as promising
alternatives to conventional assessment techniques, such as self-
report measures, studies examining consistency across these
different methodologies are limited. In a preliminary study, we
observed indications of potential discrepancies between EEG-
based and self-reported MW measures. Motivated by these
preliminary observations, our study further explores the discrep-
ancies between EEG-based and self-reported MW assessment
methods through an experiment involving visualization tasks. In
the experiment, we employ two benchmark tasks: the Visualiza-
tion Literacy Assessment Test (VLAT) and a Spatial Visualization
(SV) task. EEG signals are recorded from participants using
a 32-channel system at a sampling rate of 128 Hz during
the visualization tasks. For each participant, MW is estimated
using an EEG-based model built on a Graph Attention Network
(GAT) architecture, and these estimates are compared with
conventional MW measures to examine potential discrepancies.
Our findings reveal notable discrepancies between task difficulty
and EEG-based MW estimates, as well as between EEG-based
and self-reported MW measures across varying task difficulty
levels. Additionally, the observed patterns suggest the presence
of unconscious cognitive effort that may not be captured by self-
report alone.`,
      bibtex: `@misc{yim2025discrepanciesmentalworkloadestimation,
      title={Discrepancies in Mental Workload Estimation: Self-Reported versus EEG-Based Measures in Data Visualization Evaluation},
      author={Soobin Yim and Sangbong Yoo and Chanyoung Yoon and Chanyoung Jung and Chansoo Kim and Yun Jang and Ghulam Jilani Quadri},
      year={2025},
      eprint={2507.09262},
      archivePrefix={arXiv},
      primaryClass={cs.HC},
      url={https://arxiv.org/abs/2507.09262}
}`,
    },
  },
  {
    slug: "evaluating-line-chart",
    year: 2025,
    title:
      "Evaluating Line Chart Strategies for Mitigating Density of Temporal Data: The Impact on Trend, Prediction and Decision-Making",
    authors: [
      { name: "Rifta Ara Proma" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Paul Rosen" },
    ],
    venue:
      "In Proceedings of 20th International Symposium on Visual Computing 2025",
    links: [{ label: "PDF", href: "https://arxiv.org/abs/2510.11912" }],
    image: {
      src: "/publications/evaluating_line.png",
      alt: "Distortion Image",
    },
    detail: {
      hero: {
        src: "/publications/evaluating_line.png",
        alt: "Distortion Image",
      },
      pdf: "",
      abstract: `Overplotted line charts can obscure trends in temporal data
and hinder prediction. We conduct a user study comparing three al-
ternatives—aggregated, trellis, and spiral line charts against standard
line charts on tasks involving trend identification, making predictions,
and decision-making. We found aggregated charts performed similarly to
standard charts and support more accurate trend recognition and predic-
tion; trellis and spiral charts generally lag. We also examined the impact
on decision-making via a trust game. The results showed similar trust
in standard and aggregated charts, varied trust in spiral charts, and a
lean toward distrust in trellis charts. These findings provide guidance for
practitioners choosing visualization strategies for dense temporal data.`,
      bibtex: `@misc{proma2025evaluatinglinechartstrategies,
      title={Evaluating Line Chart Strategies for Mitigating Density of Temporal Data: The Impact on Trend, Prediction, and Decision-Making}, 
      author={Rifat Ara Proma and Ghulam Jilani Quadri and Paul Rosen},
      year={2025},
      eprint={2510.11912},
      archivePrefix={arXiv},
      primaryClass={cs.HC},
      url={https://arxiv.org/abs/2510.11912}, 
}`,
    },
  },
  // 2025
    {
    slug: "visual-edugame",
    year: 2025,
    title:
      "Animated Visual Encoding and Layer Blending for Identification of Educational Game Strategies",
    authors: [
      { name: "Braden Roper", highlight: true },
      { name: "William Thompson" },
      { name: "Chris Weaver" },

    ],
    venue:
      "To appear in IEEE Transactions on Visualization and Computer Graphics 2025.",
    image: { src: "/publications/edugame.png", alt: "Distortion Image" },
    links: [
      {
        label: "DOI",
        href: "https://doi.org/10.1109/VIS60296.2025.00069"
      },
      {
        label: "PDF",
        href: "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=11298798",
      },
    ],
    detail: {
      hero: {
        src: "/publications/edugame.png",
        alt: "Educational Game Image",
      },
      pdf: "",
      abstract: `Game-Based Learning has proven to be an effective method for enhancing engagement with educational material. However, gaining a
deeper understanding of player strategies remains challenging. Sequential game-state and action-based tracking tools often gather extensive data that can be difficult to interpret as long-term strategy.
This data presents unique problems to visualization, as it can be
fairly natural, noisy data but is constrained within synthetic, controlled environments, leading to issues such as overplotting which
can make interpretation complicated. We propose an animated visual encoding tool that utilizes kinetic visualization to address these
issues. This tool enables researchers to construct animated data narratives through the configuration of parameter interpolation curves
and blending layers. Finally, we demonstrate the usefulness of the
tool while addressing specific interests as outlined by a domain expert collaborator.`,
      bibtex: `@INPROCEEDINGS{11298798,
  author={Roper, Braden and Thompson, William and Weaver, Chris},
  booktitle={2025 IEEE Visualization and Visual Analytics (VIS)}, 
  title={Animated Visual Encoding and Layer Blending for Identification of Educational Game Strategies}, 
  year={2025},
  volume={},
  number={},
  pages={316-320},
  keywords={Interpolation;Visual analytics;Data visualization;Games;Encoding;Kinetic theory;Noise measurement;Kinetic visualization;kinetic queries;animated encoding;game-based learning},
  doi={10.1109/VIS60296.2025.00069}}
}`,
    },
  },
  {
    slug: "distortion-aware",
    year: 2025,
    title:
      "Distortion-aware Brushing for Reliable Cluster Analysis in Multidimensional Projections",
    authors: [
      { name: "Hyeon Jeon" },
      { name: "Micha  ̈el Aupetit" },
      { name: "Soohyun Lee" },
      { name: "Kwon Ko" },
      { name: "Youngtaek Kim" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Jinwook Seo" },
    ],
    venue:
      "(in press) To appear in IEEE Transactions on Visualization and Computer Graphics 2025.",
    image: { src: "/publications/distortion.png", alt: "Distortion Image" },
    links: [
      {
        label: "DOI",
        href: "https://doi.org/10.1109/TVCG.2025.3615314"
      },
      {
        label: "PDF",
        href: "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=11184260",
      },
    ],
    detail: {
      hero: {
        src: "/publications/distortion.png",
        alt: "Distortion Image",
      },
      pdf: "",
      abstract: `Brushing is a common interaction technique in 2D scatterplots, allowing users to select clustered points within a
continuous, enclosed region for further analysis or filtering. However, applying conventional brushing to 2D representations of
multidimensional (MD) data, i.e., Multidimensional Projections (MDPs), can lead to unreliable cluster analysis due to MDP-induced
distortions that inaccurately represent the cluster structure of the original MD data. To alleviate this problem, we introduce a novel
brushing technique for MDPs called Distortion-aware brushing. As users perform brushing, Distortion-aware brushing correct
distortions around the currently brushed points by dynamically relocating points in the projection, pulling data points close to the
brushed points in MD space while pushing distant ones apart. This dynamic adjustment helps users brush MD clusters more
accurately, leading to more reliable cluster analysis. Our user studies with 24 participants show that Distortion-aware brushing
significantly outperforms previous brushing techniques for MDPs in accurately separating clusters in the MD space and remains robust
against distortions. We further demonstrate the effectiveness of our technique through two use cases: (1) conducting cluster analysis
of geospatial data and (2) interactively labeling MD clusters`,
      bibtex: `@ARTICLE{jeon2026distortionawarebrushingreliableclusteranalysis,
  author={Jeon, Hyeon and Aupetit, Michaël and Lee, Soohyun and Ko, Kwon and Kim, Youngtaek and Quadri, Ghulam Jilani and Seo, Jinwook},
  journal={IEEE Transactions on Visualization and Computer Graphics},
  title={Distortion-Aware Brushing for Reliable Cluster Analysis in Multidimensional Projections},
  year={2026},
  volume={32},
  number={2},
  pages={2165-2182},
  keywords={Distortion;Brushes;Shape;Reliability;Layout;Data visualization;Visual analytics;Nonlinear distortion;Labeling;Data mining;Multidimensional projections (MDPs);distortion-aware brushing;brushing;distortions;visual clustering;cluster analysis},
  doi={10.1109/TVCG.2025.3615314}
}`,
    },
  },
  {
    slug: "understanding-bias",
    year: 2025,
    title:
      "Understanding Bias in Perceiving Dimensionality Reduction Projections",
    authors: [
      { name: "Seoyoung Doh" },
      { name: "Hyeon Jeon" },
      { name: "Sungbok Shin" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Nam Wook Kim" },
      { name: "Jinwook Seo" },
    ],
    venue:
      "In Proceedings of Workshop on Visualization for Communication (VisComm) at IEEE Transactions on Visualization and Computer Graphics 2025.",
    links: [{ label: "PDF", href: "https://arxiv.org/pdf/2507.20805" }],
    image: { src: "/publications/bias.png", alt: "Bias Image" },
    detail: {
      hero: {
        src: "/publications/bias.png",
        alt: "bias Image",
      },
      pdf: "",
      abstract: `Selecting the dimensionality reduction technique that faithfully represents the structure is essential for reliable visual communication
and analytics. In reality, however, practitioners favor projections for
other attractions, such as aesthetics and visual saliency, over the
projection’s structural faithfulness, a bias we define as visual interestingness. In this research, we conduct a user study that (1) verifies
the existence of such bias and (2) explains why the bias exists. Our
study suggests that visual interestingness biases practitioners’ preferences when selecting projections for analysis, and this bias intensifies with color-encoded labels and shorter exposure time. Based
on our findings, we discuss strategies to mitigate bias in perceiving
and interpreting DR projections.`,
      bibtex: `@misc{doh2025understandingbiasperceivingdimensionality,
      title={Understanding Bias in Perceiving Dimensionality Reduction Projections},
      author={Seoyoung Doh and Hyeon Jeon and Sungbok Shin and Ghulam Jilani Quadri and Nam Wook Kim and Jinwook Seo},
      year={2025},
      eprint={2507.20805},
      archivePrefix={arXiv},
      primaryClass={cs.HC},
      url={https://arxiv.org/abs/2507.20805}
}`,
    },
  },
  {
    slug: "subitizing-visualization",
    year: 2025,
    title:
      "Characterizing Visualization Perception with Psychological Phenomena: Uncovering the Role of Subitizing in Data Visualization",
    authors: [
      { name: "Arran Zeyu Wang" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Mengyuan Zhu" },
      { name: "Chin Tseng" },
      { name: "Danielle Albers Szafir" },
    ],
    venue:
      "In Proceedings of IEEE VIS 2025. To appear in IEEE Transactions on Visualization and Computer Graphics 2025.",
    image: { src: "/publications/char.png", alt: "Subitizing teaser" },
    links: [
      { label: "DOI", href: "https://doi.org/10.1109/TVCG.2025.3634807" },
      { label: "PDF", href: "https://arxiv.org/abs/2508.17460" },
    ],
    detail: {
      hero: {
        src: "/publications/char.png",
        alt: "Subitizing teaser",
      },
      pdf: "",
      abstract: `Understanding how people perceive visualizations is crucial for designing effective visual data representations; however, many heuristic design guidelines are derived from specific tasks or visualization types, without considering the constraints or conditions under which those guidelines hold. In this work, we aimed to assess existing design heuristics for categorical visualization using well-established psychological knowledge. Specifically, we examine the impact of the subitizing phenomenon in cognitive psychology—people’s ability to automatically recognize a small set of objects instantly without counting—in data visualizations. We conducted three experiments with multi-class scatterplots—between 2 and 15 classes with varying design choices—across three different tasks—class estimation, correlation comparison, and clustering judgments—to understand how performance changes as the number of classes (and therefore set size) increases. Our results indicate if the category number is smaller than six, people tend to perform well at all tasks, providing empirical evidence of subitizing in visualization. When category numbers increased, performance fell, with the magnitude of the performance change depending on task and encoding. Our study bridges the gap between heuristic guidelines and empirical evidence by applying well-established psychological theories, suggesting future opportunities for using psychological theories and constructs to characterize visualization perception.`,
      bibtex: `@ARTICLE{wang2026characterizingvisualizationperceptionpsychologicalphenomena,
  author={Wang, Arran Zeyu and Quadri, Ghulam Jilani and Zhu, Mengyuan and Tseng, Chin and Szafir, Danielle Albers},
  journal={IEEE Transactions on Visualization and Computer Graphics},
  title={Characterizing Visualization Perception with Psychological Phenomena: Uncovering the Role of Subitizing in Data Visualization},
  year={2026},
  volume={32},
  number={1},
  pages={1131-1141},
  keywords={Data visualization;Image color analysis;Encoding;Shape;Psychology;Visualization;Accuracy;Guidelines;Design methodology;Estimation;Visualization Perception;Psychology;Subitizing;Fechner's Law;Dual-System Theory;Categorical Data;Color;Shape},
  doi={10.1109/TVCG.2025.3634807}
}`,
    },
    highlight: "Best Paper Honorable Mention (IEEE VIS 2025)",
  },
  {
    slug: "annotation-survey-2025",
    year: 2025,
    title:
      "A Survey on Annotations in Information Visualization: Empirical Insights, Applications, and Challenges",
    authors: [
      { name: "Md Dilshadur Rahman" },
      { name: "Bhavana Doppalapudi" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Paul Rosen" },
    ],
    venue:
      "(in press) To appear in IEEE Transactions on Visualization and Computer Graphics 2025.",
    image: {
      src: "/publications/annotations.png",
      alt: "Annotation survey",
    },
    links: [
      { label: "DOI", href: "https://arxiv.org/abs/2410.05579" },
      { label: "PDF", href: "https://arxiv.org/pdf/2410.05579" },
    ],
    detail: {
      hero: {
        src: "/publications/publication_1.png",
        alt: "Annotation survey teaser",
      },
      pdf: "https://arxiv.org/pdf/2410.05579",
      abstract: `We present a comprehensive survey on the use of annotations in information visualization, highlighting their crucial role in improving audience understanding and engagement with visual data. Our investigation encompasses empirical studies on annotations, showcasing their impact on user engagement, interaction, comprehension, and memorability across various contexts. We also study existing tools and techniques for creating annotations and their diverse applications, enhancing understanding of both practical and theoretical aspects. Additionally, we identify research gaps and propose potential future research directions, making this survey a resource for researchers, visualization designers, and practitioners. An interactive web resource detailing the surveyed papers is available at https://shape-vis.github.io/annotation_star/.`,
      bibtex: `@article{mdrahman2025survey,
  title   = {A Survey on Annotations in Information Visualization: Empirical Insights, Applications, and Challenges},
  author  = {Rahman, Md Dilshadur and Doppalapudi, Bhavana and Quadri, Ghulam Jilani and Rosen, Paul},
  journal = {IEEE Transactions on Visualization and Computer Graphics},
  year    = {2025},
  doi     = {10.48550/arXiv.2410.05579}
}`,
    },
  },
  // 2024
  {
    slug: "shape-it-up",
    year: 2024,
    title:
      "Shape It Up: An Empirically Grounded Approach for Designing Shape Palettes",
    authors: [
      { name: "Chin Tseng" },
      { name: "Arran Zeyu Wang" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Danielle Albers Szafir" },
    ],
    venue:
      "In Proceedings of IEEE VIS 2024; published in IEEE Transactions on Visualization and Computer Graphics 2025.",
    image: { src: "/publications/shape.png", alt: "Shape It Up" },
    links: [
      {
        label: "DOI",
        href: "https://ieeexplore.ieee.org/abstract/document/10681156",
      },
      { label: "PDF", href: "https://arxiv.org/pdf/2408.16079" },
      { label: "Shape Tool", href: "https://shape-it-up-eec5e.web.app/" },
    ],
    detail: {
      hero: { src: "/publications/shape.png", alt: "Shape It Up teaser" },
      pdf: "https://arxiv.org/pdf/2408.16079",
      abstract: `Shape is commonly used to distinguish between categories in multi-class scatterplots. However, we lack empirically-validated guidance for creating shape palettes that support effective perception. We present a series of three crowdsourced experiments studying how shape characteristics affect category identification in scatterplots. Our experiments measure how shape characteristics including geometry, fill, and orientation affect people's ability to identify point categories quickly and accurately. We find that shape perception is influenced by multiple factors, including a shape's geometric properties and its rendered size. Based on these findings, we derive a set of design guidelines for creating effective shape palettes and demonstrate their application in a proof-of-concept tool for generating shape palettes based on our experimental results.`,
      bibtex: `@ARTICLE{10681156,
  author={Tseng, Chin and Wang, Arran Zeyu and Quadri, Ghulam Jilani and Szafir, Danielle Albers},
  journal={IEEE Transactions on Visualization and Computer Graphics}, 
  title={Shape It Up: An Empirically Grounded Approach for Designing Shape Palettes}, 
  year={2025},
  volume={31},
  number={1},
  pages={349-359},
  keywords={Shape;Image color analysis;Data visualization;Visualization;Encoding;Data models;Guidelines;Categorical perception;shape perception;multiclass scatterplots;visualization effectiveness;quantitative study},
  doi={10.1109/TVCG.2024.3456385}
}`,
    },
  },
  {
    slug: "annotation-design-space",
    year: 2024,
    title:
      "A Qualitative Analysis of Common Practices in Annotations: A Taxonomy and Design Space",
    authors: [
      { name: "Dilshad ur Rahman" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Bhavana Doppalapudi" },
      { name: "Danielle Albers Szafir" },
      { name: "Paul Rosen" },
    ],
    venue:
      "In Proceedings of IEEE VIS 2024; published in IEEE Transactions on Visualization and Computer Graphics 2025.",
    image: {
      src: "/publications/publication_2.png",
      alt: "Annotation design space",
    },
    links: [
      {
        label: "DOI",
        href: "https://ieeexplore.ieee.org/abstract/document/10670067",
      },
      { label: "PDF", href: "https://arxiv.org/pdf/2306.06043" },
      {
        label: "Data",
        href: "https://osf.io/e5zq9/?view_only=173a644eb5d3448c832408baf3b050b0",
      },
    ],
    detail: {
      hero: {
        src: "/publications/publication_2.png",
        alt: "Annotation design space teaser",
      },
      pdf: "https://arxiv.org/pdf/2306.06043",
      abstract: `Annotations play a vital role in highlighting critical aspects of visualizations, aiding in data externalization and exploration, collaborative sensemaking, and visual storytelling. However, despite their widespread use, we identified a lack of a design space for common practices for annotations. In this paper, we evaluated over 1,800 static annotated charts to understand how people annotate visualizations in practice. Through qualitative coding of these diverse real-world annotated charts, we explored three primary aspects of annotation usage patterns: analytic purposes for chart annotations (e.g., present, identify, summarize, or compare data features), mechanisms for chart annotations (e.g., types and combinations of annotations used, frequency of different annotation types across chart types, etc.), and the data source used to generate the annotations. We then synthesized our findings into a design space of annotations, highlighting key design choices for chart annotations. We presented three case studies illustrating our design space as a practical framework for chart annotations to enhance the communication of visualization insights. All supplemental materials are available at https://shorturl.at/bAGM1.`,
      bibtex: `@ARTICLE{10670067,
  author={Rahman, Md Dilshadur and Quadri, Ghulam Jilani and Doppalapudi, Bhavana and Szafir, Danielle Albers and Rosen, Paul},
  journal={IEEE Transactions on Visualization and Computer Graphics}, 
  title={A Qualitative Analysis of Common Practices in Annotations: A Taxonomy and Design Space}, 
  year={2025},
  volume={31},
  number={1},
  pages={360-370},
  keywords={Annotations;Data visualization;Connectors;Visualization;Collaboration;Image color analysis;Electronic mail;Annotations;visualizations;qualitative study;design space;taxonomy},
  doi={10.1109/TVCG.2024.3456359}}`,
    },
  },
  {
    slug: "evaluation-method-balance",
    year: 2024,
    title:
      "Striking the Right Balance: Systematic Assessment of Evaluation Method Distribution Across Contribution Types",
    authors: [
      { name: "Feng Lin" },
      { name: "Arran Zeyu Wang" },
      { name: "Dilshad ur Rahman" },
      { name: "Danielle Albers Szafir" },
      { name: "Ghulam Jilani Quadri", highlight: true },
    ],
    venue: "In Proceedings of BELIV Workshop at IEEE VIS 2024.",
    image: {
      src: "/publications/publication_3.png",
      alt: "Evaluation method balance",
    },
    links: [
      {
        label: "DOI",
        href: "https://www.computer.org/csdl/proceedings-article/beliv/2024/284600a129/22a0EOOwpQA",
      },
      { label: "Preprint", href: "https://arxiv.org/pdf/2408.16080" },
    ],
    detail: {
      hero: {
        src: "/publications/publication_3.png",
        alt: "Evaluation method balance teaser",
      },
      pdf: "https://arxiv.org/pdf/2408.16080",
      abstract: `In the rapidly evolving field of information visualization, rigorous evaluation is essential for validating new techniques, understanding user interactions, and demonstrating the effectiveness and usability of visualizations. Faithful evaluations provide valuable insights into how users interact with and perceive the system, enabling designers to identify potential weaknesses and make informed decisions about design choices and improvements. However, an emerging trend of multiple evaluations within a single research raises critical questions about the sustainability, feasibility, and methodological rigor of such an approach. New researchers and students, influenced by this trend, may believe that multiple evaluations are necessary for a study, regardless of the contribution types. However, the number of evaluations in a study should depend on its contributions and merits, not on the trend of including multiple evaluations to strengthen a paper. So, how many evaluations are enough? This is a situational question and cannot be formulaically determined. Our objective is to summarize current trends and patterns to assess the distribution of evaluation methods over different paper contribution types. In this paper, we identify this trend through a non-exhaustive literature survey of evaluation patterns in 214 papers in the two most recent years’ VIS issues in IEEE TVCG from 2023 and 2024. We then discuss various evaluation strategy patterns in the information visualization field to guide practical choices and how this paper will open avenues for further discussion.`,
      bibtex: `@INPROCEEDINGS{10756059,
  author    = {Lin, Feng and Wang, Arran Zeyu and Rahman, Md Dilshadur and Szafir, Danielle Albers and Quadri, Ghulam Jilani},
  booktitle = {2024 IEEE Evaluation and Beyond - Methodological Approaches for Visualization (BELIV)},
  title     = {Striking the Right Balance: Systematic Assessment of Evaluation Method Distribution Across Contribution Types},
  year      = {2024},
  pages     = {129-135},
  abstract  = {In the rapidly evolving field of information visualization, rigorous evaluation is essential for validating new techniques, understanding user interactions, and demonstrating the effectiveness and usability of visualizations. Faithful evaluations provide valuable insights into how users interact with and perceive the system, enabling designers to identify potential weaknesses and make informed decisions about design choices and improvements. However, an emerging trend of multiple evaluations within a single research raises critical questions about the sustainability, feasibility, and methodological rigor of such an approach. New researchers and students, influenced by this trend, may believe - multiple evaluations are necessary for a study, regardless of the contribution types. However, the number of evaluations in a study should depend on its contributions and merits, not on the trend of including multiple evaluations to strengthen a paper. So, how many evaluations are enough? This is a situational question and cannot be formulaically determined. Our objective is to summarize current trends and patterns to assess the distribution of evaluation methods over different paper contribution types. In this paper, we identify this trend through a non-exhaustive literature survey of evaluation patterns in 214 papers in the two most recent years' VIS issues in IEEE TVCG from 2023 and 2024. We then discuss various evaluation strategy patterns in the information visualization field to guide practical choices and how this paper will open avenues for further discussion.},
  keywords  = {Surveys; Visualization; Technological innovation; Systematics; Reviews; Market research; Complexity theory; Reliability; Usability; Sustainable development},
  doi       = {10.1109/BELIV64461.2024.00020},
  url       = {https://doi.ieeecomputersociety.org/10.1109/BELIV64461.2024.00020},
  publisher = {IEEE Computer Society},
  address   = {Los Alamitos, CA, USA},
  month     = {Oct}
}`,
    },
  },
  {
    slug: "our-stories-our-data",
    year: 2024,
    title:
      "Our Stories, Our Data: Co-designing Visualizations with People with Intellectual and Developmental Disabilities",
    authors: [
      { name: "Keke Wu" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Arran Zeyu Wang" },
      { name: "David Kwame Osei-Tutu" },
      { name: "Emma Peterson" },
      { name: "Varsha Koushik" },
      { name: "Danielle Albers Szafir" },
    ],
    venue:
      "In the Proceedings of ACM SIGACCESS Conference on Computers and Accessibility, 2024.",
    image: {
      src: "/publications/publication_4.png",
      alt: "Our Stories Our Data",
    },
    links: [
      {
        label: "DOI",
        href: "https://dl.acm.org/doi/abs/10.1145/3663548.3675615",
      },
      { label: "Preprint", href: "https://arxiv.org/pdf/2408.16072" },
    ],
    detail: {
      hero: {
        src: "/publications/publication_4.png",
        alt: "Our Stories Our Data teaser",
      },
      pdf: "https://arxiv.org/pdf/2408.16072",
      abstract: `Individuals with Intellectual and Developmental Disabilities (IDD) have unique needs and challenges when working with data. While visualization aims to make data more accessible to a broad audience, our understanding of how to design cognitively accessible visualizations remains limited. In this study, we engaged 20 participants with IDD as co-designers to explore how they approach and visualize data. Our preliminary investigation paired four participants as data pen-pals in a six-week online asynchronous participatory design workshop. In response to the observed conceptual, technological, and emotional struggles with data, we subsequently organized a two-day in-person co-design workshop with 16 participants to further understand relevant visualization authoring and sensemaking strategies. Reflecting on how participants engaged with and represented data, we propose two strategies for cognitively accessible data visualizations: transforming numbers into narratives and blending data design with everyday aesthetics. Our findings emphasize the importance of involving individuals with IDD in the design process, demonstrating their capacity for data analysis and expression, and underscoring the need for a narrative and tangible approach to accessible data visualization.`,
      bibtex: `@inproceedings{Wu_2024, series={ASSETS ’24},
  title={Our Stories, Our Data: Co-designing Visualizations with People with Intellectual and Developmental Disabilities},
  url={http://dx.doi.org/10.1145/3663548.3675615},
  DOI={10.1145/3663548.3675615},
  booktitle={The 26th International ACM SIGACCESS Conference on Computers and Accessibility},
  publisher={ACM},
  author={Wu, Keke and Quadri, Ghulam Jilani and Wang, Arran Zeyu and Osei-Tutu, David Kwame and Petersen, Emma and Koushik, Varsha and Szafir, Danielle Albers},
  year={2024},
  month=oct,
  pages={1–17},
  collection={ASSETS ’24}
}`,
    },
  },
  {
    slug: "annotation-barchart",
    year: 2024,
    title:
      "Exploring Annotation Taxonomy in Grouped Bar Charts: A Qualitative Classroom Study",
    authors: [
      { name: "Dilshad ur Rahman" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Danielle Albers Szafir" },
      { name: "Paul Rosen" },
    ],
    venue: "Information Visualization, 2024.",
    image: {
      src: "/publications/publication_5.png",
      alt: "Grouped bar chart annotations",
    },
    links: [
      {
        label: "DOI",
        href: "https://journals.sagepub.com/doi/epdf/10.1177/14738716241270247",
      },
    ],
    detail: {
      pdf: "https://journals.sagepub.com/doi/epdf/10.1177/14738716241270247",
    },
  },
  {
    slug: "task-design-optimized",
    year: 2024,
    title:
      "Toward Constructing Frameworks for Task- and Design-Optimized Visualizations",
    authors: [{ name: "Ghulam Jilani Quadri", highlight: true }],
    venue: "IEEE Computer Graphics and Applications (CG&A), 2024.",
    image: {
      src: "/publications/publication_6.png",
      alt: "Task & design optimized",
    },
    links: [
      { label: "DOI", href: "https://ieeexplore.ieee.org/document/10736168" },
    ],
    detail: {
      hero: {
        src: "/publications/publication_6.png",
        alt: "Task & design optimized teaser",
      },
      pdf: "https://ieeexplore.ieee.org/document/10736168",
      abstract: `Visualization is crucial to augment and enhance human understanding and decision-making in today’s data-driven world. However, the way data are visualized can influence and drastically change the conclusions people draw using data. The findings around visualization effectiveness are nuanced, and guidelines for effective visualization design depend on the visual channels used, chart types, and analysis tasks. This points to a significant need to understand the intersection of these factors to create optimized visualizations. We need a framework to define this intersection that fills the gap by providing a task-optimized visualization design for better quality and higher decision-making confidence that gives designers objective guidance. A task-optimized visualization design framework strategically integrates visual channels, visualization types, and specific low-level tasks to enhance data interpretation and optimize user task performance. We discuss constructing a visualization framework that considers both human perception for encoding techniques and the task being performed, enabling optimizing visualization design to maximize efficiency. Furthermore, we highlight a task-optimized framework’s impact and potential applications.`,
      bibtex: `@ARTICLE{10736168,
  author={Quadri, Ghulam Jilani},
  journal={IEEE Computer Graphics and Applications}, 
  title={Toward Constructing Frameworks for Task- and Design-Optimized Visualizations}, 
  year={2024},
  volume={44},
  number={5},
  pages={104-113},
  keywords={Visualization;Decision making;Data visualization;Encoding;Guidelines},
  doi={10.1109/MCG.2024.3429828}
}`,
    },
  },
  {
    slug: "do-you-see-what-i-see",
    year: 2024,
    title:
      "Do You See What I See? A Qualitative Study Eliciting High-Level Visualization Comprehension",
    authors: [
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Arran Zeyu Wang" },
      { name: "Zhehao Wang" },
      { name: "Jennifer Adorno" },
      { name: "Paul Rosen" },
      { name: "Danielle Albers Szafir" },
    ],
    venue:
      "In Proceedings of ACM CHI 2024: ACM Conference on Human Factors in Computing Systems, 2024.",
    image: {
      src: "/publications/publication_7.png",
      alt: "High-level comprehension",
    },
    links: [
      { label: "DOI", href: "https://dl.acm.org/doi/10.1145/3613904.3642813" },
      { label: "PDF", href: "https://arxiv.org/pdf/2402.15605" },
      { label: "Data", href: "https://osf.io/869ev/" },
    ],
    detail: {
      hero: {
        src: "/publications/publication_7.png",
        alt: "High-level comprehension teaser",
      },
      pdf: "https://arxiv.org/pdf/2402.15605",
      abstract: `Designers often create visualizations to achieve specific high-level analytical or communication goals. These goals require people to naturally extract complex, contextualized, and interconnected patterns in data. While limited prior work has studied general high-level interpretation, prevailing perceptual studies of visualization effectiveness primarily focus on isolated, predefined, low-level tasks, such as estimating statistical quantities. This study more holistically explores visualization interpretation to examine the alignment between designers’ communicative goals and what their audience sees in a visualization, which we refer to as their comprehension. We found that statistics people effectively estimate from visualizations in classical graphical perception studies may differ from the patterns people intuitively comprehend in a visualization. We conducted a qualitative study on three types of visualizations—line graphs, bar graphs, and scatterplots—to investigate the high-level patterns people naturally draw from a visualization. Participants described a series of graphs using natural language and think-aloud protocols. We found that comprehension varies with a range of factors, including graph complexity and data distribution. Specifically, 1) a visualization’s stated objective often does not align with people’s comprehension, 2) results from traditional experiments may not predict the knowledge people build with a graph, and 3) chart type alone is insufficient to predict the information people extract from a graph. Our study confirms the importance of defining visualization effectiveness from multiple perspectives to assess and inform visualization practices.`,
      bibtex: `@inproceedings{10.1145/3613904.3642813,
author = {Quadri, Ghulam Jilani and Wang, Arran Zeyu and Wang, Zhehao and Adorno, Jennifer and Rosen, Paul and Szafir, Danielle Albers},
title = {Do You See What I See? A Qualitative Study Eliciting High-Level Visualization Comprehension},
year = {2024},
isbn = {9798400703300},
publisher = {Association for Computing Machinery},
address = {New York, NY, USA},
url = {https://doi.org/10.1145/3613904.3642813},
doi = {10.1145/3613904.3642813},
abstract = {Designers often create visualizations to achieve specific high-level analytical or communication goals. These goals require people to naturally extract complex, contextualized, and interconnected patterns in data. While limited prior work has studied general high-level interpretation, prevailing perceptual studies of visualization effectiveness primarily focus on isolated, predefined, low-level tasks, such as estimating statistical quantities. This study more holistically explores visualization interpretation to examine the alignment between designers’ communicative goals and what their audience sees in a visualization, which we refer to as their comprehension. We found that statistics people effectively estimate from visualizations in classical graphical perception studies may differ from the patterns people intuitively comprehend in a visualization. We conducted a qualitative study on three types of visualizations—line graphs, bar graphs, and scatterplots—to investigate the high-level patterns people naturally draw from a visualization. Participants described a series of graphs using natural language and think-aloud protocols. We found that comprehension varies with a range of factors, including graph complexity and data distribution. Specifically, 1) a visualization’s stated objective often does not align with people’s comprehension, 2) results from traditional experiments may not predict the knowledge people build with a graph, and 3) chart type alone is insufficient to predict the information people extract from a graph. Our study confirms the importance of defining visualization effectiveness from multiple perspectives to assess and inform visualization practices.},
booktitle = {Proceedings of the 2024 CHI Conference on Human Factors in Computing Systems},
articleno = {204},
numpages = {26},
keywords = {Communicative goals, High-level comprehension, Insight, Qualitative evaluation, Visualization},
location = {Honolulu, HI, USA},
series = {CHI '24}
}`,
    },
  },
  {
    slug: "categorical-color-perception",
    year: 2024,
    title:
      "Revisiting Categorical Color Perception in Scatterplots: Sequential, Diverging, and Categorical Palettes",
    authors: [
      { name: "Chin Tseng" },
      { name: "Arran Zeyu Wang" },
      { name: "Ghulam Jilani Quadri", highlight: true },
      { name: "Danielle Albers Szafir" },
    ],
    venue:
      "In Proceedings of EG/VGTC European Conference on Visualization (EuroVis) 2024, Odense, Denmark.",
    image: {
      src: "/publications/publication_8.png",
      alt: "Categorical color perception",
    },
    highlight: "Best Short Paper Award (Top 1% submissions)",
    links: [
      {
        label: "DOI",
        href: "https://diglib.eg.org/items/1f3ab945-36dc-4e43-ac70-5d152cef3dc0",
      },
      { label: "Preprint", href: "https://arxiv.org/pdf/2404.03787" },
      { label: "EuroVis News", href: "https://event.sdu.dk/eurovis/awards" },
    ],
    detail: {
      hero: {
        src: "/publications/publication_8.png",
        alt: "Categorical color perception teaser",
      },
      pdf: "https://arxiv.org/pdf/2404.03787",
      abstract: `Existing guidelines for categorical color selection are heuristic, often grounded in intuition rather than empirical studies of readers' abilities. While design conventions recommend palettes maximize hue differences, more recent exploratory findings indicate other factors, such as lightness, may play a role in effective categorical palette design. We conducted a crowdsourced experiment on mean value judgments in multi-class scatterplots using five color palette families—single-hue sequential, multihue sequential, perceptually-uniform multi-hue sequential, diverging, and multi-hue categorical—that differ in how they manipulate hue and lightness. Participants estimated relative mean positions in scatterplots containing 2 to 10 categories using 20 colormaps. Our results confirm heuristic guidance that hue-based categorical palettes are most effective. However, they also provide additional evidence that scalable categorical encoding relies on more than hue variance.`,
      bibtex: `@inproceedings{10.2312:evs.20241073,
booktitle = {EuroVis 2024 - Short Papers},
editor = {Tominski, Christian and Waldner, Manuela and Wang, Bei},
title = {{Revisiting Categorical Color Perception in Scatterplots: Sequential, Diverging, and Categorical Palettes}},
author = {Tseng, Chin and Wang, Arran Zeyu and Quadri, Ghulam Jilani and Szafir, Danielle Albers},
year = {2024},
publisher = {The Eurographics Association},
ISBN = {978-3-03868-251-6},
DOI = {10.2312/evs.20241073}
}`,
    },
  },

  {
    slug: "clams",
    year: 2024,
    title:
      "CLAMS: Cluster Ambiguity Measure for Estimating Perceptual Variability in Visual Clustering",
    authors: [
      { name: "Hyeon Jeon*" },
      { name: "Ghulam Jilani Quadri*", highlight: true },
      { name: "Hyunwook Lee" },
      { name: "Paul Rosen" },
      { name: "Danielle Albers Szafir" },
      { name: "Jinwook Seo" },
    ],
    venue:
      "IEEE Transactions on Visualization & Computer Graphics (Proc. IEEE VIS 2023), 2024.",
    image: { src: "/projects/project_3.png", alt: "CLAMS" },
    links: [
      {
        label: "DOI",
        href: "https://journals.sagepub.com/doi/epdf/10.1177/14738716241270247",
      },
      { label: "Preprint", href: "https://arxiv.org/pdf/2308.00284" },
      {
        label: "UNC-News",
        href: "https://cs.unc.edu/news-article/visualab-earns-2-best-paper-honorable-mention-awards-at-ieee-vis/",
      },
      {
        label: "Demo",
        href: "http://clusterambiguity.dev.s3-website.ap-northeast-2.amazonaws.com/",
      },
    ],
    detail: {
      hero: { src: "/projects/project_3.png", alt: "CLAMS Overview" },
      pdf: "https://arxiv.org/pdf/2308.00284",
      abstract: `Visual clustering is a common perceptual task in scatterplots that supports diverse analytics tasks (e.g., cluster identification). However, even with the same scatterplot, the ways of perceiving clusters (i.e., conducting visual clustering) can differ due to the differences among individuals. Although such perceptual variability casts doubt on the reliability of data analysis based on visual clustering, we lack a systematic way to efficiently assess this variability. In this research, we study perceptual variability in conducting visual clustering, which we call "Cluster Ambiguity". To this end, we introduce "CLAMS", a data-driven visual quality measure for automatically predicting cluster ambiguity in monochrome scatterplots. We first conduct a qualitative study to identify key factors that affect the visual separation of clusters (e.g., proximity or size difference between clusters). Based on the study findings, we deploy a regression module that estimates the human-judged separability of two clusters. Then, CLAMS predicts cluster ambiguity by analyzing the aggregated results of all pairwise separability between clusters that are generated by the module. CLAMS outperforms widely-used clustering techniques in predicting ground truth cluster ambiguity. Meanwhile, CLAMS exhibits performance on par with human annotators. We conclude our work by presenting two applications for optimizing and benchmarking data mining techniques using CLAMS.`,
      bibtex: `@ARTICLE{10308641,
  author={Jeon, Hyeon and Quadri, Ghulam Jilani and Lee, Hyunwook and Rosen, Paul and Szafir, Danielle Albers and Seo, Jinwook},
  journal={IEEE Transactions on Visualization and Computer Graphics},
  title={CLAMS: A Cluster Ambiguity Measure for Estimating Perceptual Variability in Visual Clustering},
  year={2024},
  volume={30},
  number={1},
  pages={770-780},
  keywords={Visualization;Task analysis;Reliability;Benchmark testing;Data analysis;Complexity theory;Clustering algorithms;Cluster;scatterplot;perception;cluster analysis;cluster ambiguity;visual quality measure},
  doi={10.1109/TVCG.2023.3327201}
}`,
    },
    highlight: "Best Paper Honorable Mention (IEEE VIS 2023)",
  },
];
